name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello and welcome! Thank you for taking part in the development of Flux! Your support is much appreciated."
        pr-message: "Hello and welcome! Thank you for taking part in the development of Flux! Your support is much appreciated."
