name: Windows CI

on:
  push:
    paths:
      - 'flux.cpp'
      - '.github/workflows/win-ci.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest
      - name: Build Flux
        run: g++ flux.cpp -o flux -Ofast -Wall -Wextra -Wno-multichar -Wno-overflow
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Build artifact
          path: flux.exe
